var data = {
    "premiums": [
        {
            "id": 1,
            "name": "HBO",
            "aacURL": "http://agentanswercenter.directv.com/en-us/res/programming/hbo.html",
            "dotcomURL": "http://www.directv.com/premiums/hbo",
            "premURL": "http://www.hbo.com/",
            "price": "17.99",
            "ODchan": "1501",
            "channels": [
                {
                    "name": "Showtime East",
                    "description": "East Coast feed. Experience the ultimate in home theater entertainment with Showtime.",
                    "number": "545",
                    "HD": "TRUE",
                    "SD": "TRUE"
                }
            ],
            "sellingpoints": [
                {
                    "subtab": "Overview",
                    "title": "N/A",
                    "sellingPoint": "Thirteen commercial-free channels with award winning original series, uncut hit movies, year round sports, documentaries and comedy specials",
                    "evergreen": "true"
                }
            ],
            "subs": [
                1,
                2,
                3,
                6
            ],
            "subtabs": [
                {
                    "id": 1,
                    "name": "Overview"
                },
                {
                    "id": 2,
                    "name": "Movies"
                },
                {
                    "id": 3,
                    "name": "Original Programming"
                },
                {
                    "id": 4,
                    "name": "Streaming"
                },
                {
                    "id": 5,
                    "name": "DIRECTV On Demand"
                },
                {
                    "id": 6,
                    "name": "Channels"
                }
            ],
            "calendars": [
                {
                    "program": "Shameless",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/10/16",
                    "dayWeek": "Sunday",
                    "finDate": "04/03/16",
                    "repDates": null,
                    "startOD": "01/10/16",
                    "keyDemos": "adults 18-49",
                    "genres": "Comedy",
                    "starActrs": "William H. Macy and Emmy Rossum",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "The Gallagher's are finally getting their act together and striking out on their own, but growing up could also mean growing apart.",
                    "image": "Shameless Season 6 Version B Key Art - Horizontal"
                },
                {
                    "program": "Billions",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/17/16",
                    "dayWeek": "Sunday",
                    "finDate": "04/10/16",
                    "repDates": null,
                    "startOD": "01/17/16",
                    "keyDemos": "adults 35+",
                    "genres": "Drama",
                    "starActrs": "Paul Giamatti and Damien Lewis",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Paul Giamatti and Damien Lewis star in this complex drama about power politics in the world of New York high finance.",
                    "image": "Billions Season 1 Key Art (Horizontal)"
                },
                {
                    "program": "Dark Net",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/21/16",
                    "dayWeek": "Thursday",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/21/16",
                    "keyDemos": null,
                    "genres": "Documentary",
                    "starActrs": "TBD",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "DARK NET will explore unique themes of the web and uncover different tales of real people who have been affected by them. ",
                    "image": "Dark Net Key Art"
                },
                {
                    "program": "The Circus: Inside the Greatest Political Show on Earth",
                    "premium": "Showtime ",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "TBD",
                    "dayWeek": "TBD",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "TB/D/",
                    "keyDemos": null,
                    "genres": "News/Documentary ",
                    "starActrs": null,
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Showtime is jumping into politics in THE CIRCUS: INSIDE THE GREATEST POLITICAL SHOW ON EARTH, a series which provides intimate behind the scenes access to the high human drama inherent in the pursuit of the Oval Office.",
                    "image": "TheCircus"
                },
                {
                    "program": "The Imitation Game",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/15/16",
                    "dayWeek": "Friday",
                    "finDate": null,
                    "repDates": "012116, 012716, 013016",
                    "startOD": "01/15/16",
                    "keyDemos": null,
                    "genres": "Historical Drama",
                    "starActrs": "Benedict Cumberbatch and Keira Knightley",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "During World War II, mathematician Alan Turing tries to crack the enigma code with help from fellow mathematicians.",
                    "image": "Imitation Game, The - unit 1"
                },
                {
                    "program": "The Hundred-Foot Journey",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/08/16",
                    "dayWeek": "Friday",
                    "finDate": null,
                    "repDates": "011116, 011616, 012116",
                    "startOD": "01/08/16",
                    "keyDemos": null,
                    "genres": "Comedy",
                    "starActrs": "Helen Mirren",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "The Kadam family leaves India for France where they open a restaurant directly across the road from Madame Mallory's Michelin-starred eatery.",
                    "image": "Hundred-Foot Journey, The - Key Art (horizontal)"
                },
                {
                    "program": "Drunk Stoned Brilliant Dead: The Story of the National Lampoon",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/22/16",
                    "dayWeek": "Friday",
                    "finDate": null,
                    "repDates": "012716",
                    "startOD": "01/22/16",
                    "keyDemos": null,
                    "genres": "Documentary",
                    "starActrs": null,
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "DRUNK STONED BRILLIANT DEAD tells the story of how America’s first adult humor magazine, changed comedy forever before the magazine’s spectacular fall.",
                    "image": "Drunk stoned brilliant dead... - unit 1"
                },
                {
                    "program": "Inside the NFL",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/05/16",
                    "dayWeek": "Tuesday",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/05/16",
                    "keyDemos": null,
                    "genres": "Sports",
                    "starActrs": null,
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "The Emmy winning weekly show with the most experienced and connected analysts in the business. Get expert insight, exclusive commentary and special on and off the field features.",
                    "image": "Inside the NFL S8 (Horizontal)"
                },
                {
                    "program": "60 Minutes Sports",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/05/16",
                    "dayWeek": "Tuesday",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/05/16",
                    "keyDemos": null,
                    "genres": "Sports",
                    "starActrs": null,
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "The award-winning team behind 60 Minutes now turns its investigative eye towards the world of sports. ",
                    "image": "60 Minutes Sports Key Art - Horizontal"
                },
                {
                    "program": "SHO Champtionship Boxing",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/16/16",
                    "dayWeek": "Saturday",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/16/16",
                    "keyDemos": null,
                    "genres": "Sports",
                    "starActrs": null,
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Undefeated WBC Heavyweight World Champion Deontay Wilder will make the third defense of his title against brawling Polish contender Artur Szpilka.",
                    "image": "Wilder horizontal"
                },
                {
                    "program": "The To Do List",
                    "premium": "Showtime",
                    "chanName": "THE MOVIE CHANNEL XTRA",
                    "chanNum": "555",
                    "premDate": "01/04/16",
                    "dayWeek": "Monday",
                    "finDate": null,
                    "repDates": "010916, 011216",
                    "startOD": "01/04/16",
                    "keyDemos": null,
                    "genres": "Comedy",
                    "starActrs": "Aubrey Plaza, Rachel Bilson and Andy Samberg",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "All-star comedy about a type-A teenage girl who tries to shed her uptight image by undertaking a list of all the outrageous activities she missed out on in high school, before she goes to college. ",
                    "image": null
                },
                {
                    "program": "Camp X-Ray",
                    "premium": "Showtime",
                    "chanName": "THE MOVIE CHANNEL",
                    "chanNum": "543 (East) 544 (West)",
                    "premDate": "01/16/16",
                    "dayWeek": "Saturday",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/16/16",
                    "keyDemos": null,
                    "genres": "Drama",
                    "starActrs": "Kristin Stewart ",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Kristen Stewart stars as a young woman who joins the military to escape her small town roots but ends up as a rookie guard at Guantanamo Bay where she strikes up an unusual and life changing friendship with one of the detainees.",
                    "image": null
                },
                {
                    "program": "The Lovely Bones",
                    "premium": "Showtime",
                    "chanName": "THE MOVIE CHANNEL ",
                    "chanNum": "543 (East) 544 (West)",
                    "premDate": "01/01/16",
                    "dayWeek": "Friday",
                    "finDate": null,
                    "repDates": "010316,010516,010816",
                    "startOD": "01/01/16",
                    "keyDemos": null,
                    "genres": "Mystery/Thriller",
                    "starActrs": "Mark Wahlberg, Rachel Weisz, Susan Sarandon",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Peter Jackson directs this extraordinary story narrated by a murdered 14-year-old girl from a strange and beautiful in-between afterlife, who must help her father catch her killer and protect her family before she can move on.",
                    "image": null
                },
                {
                    "program": "Frank Miller's Sin City: A Dame to Kill For",
                    "premium": "Showtime",
                    "chanName": "Showtime East HD",
                    "chanNum": "545",
                    "premDate": "01/02/16",
                    "dayWeek": "Saturday ",
                    "finDate": null,
                    "repDates": "010316,010516,010816",
                    "startOD": "01/02/16",
                    "keyDemos": null,
                    "genres": "Action",
                    "starActrs": "Jessica Alba, Joseph Gordon-Levitt and Eva Green",
                    "starDrctrs": "Frank",
                    "starPrdcrs": null,
                    "description": "Frank Miller's classic graphic novels return to the screen, weaving together gritty tales that feature Basin City's most hardboiled citizens as they cross paths with the town's more notorious inhabitants. ",
                    "image": null
                },
                {
                    "program": "Need for Speed",
                    "premium": "Showtime",
                    "chanName": "Showtime Extreme ",
                    "chanNum": "549",
                    "premDate": "01/03/16",
                    "dayWeek": "Sunday ",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/03/16",
                    "keyDemos": null,
                    "genres": "Action",
                    "starActrs": "Aaron Paul and Dominic Cooper",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Aaron Paul stars as a street racer who was framed by a wealthy business associate. Now, fresh from prison, he gets his hands on the fastest car around and joins a secretive and extremely high stakes race with revenge in mind.",
                    "image": null
                },
                {
                    "program": "Snowpiercer ",
                    "premium": "Showtime",
                    "chanName": "Showtime Beyond",
                    "chanNum": "550",
                    "premDate": "01/01/16",
                    "dayWeek": "Friday ",
                    "finDate": null,
                    "repDates": "010516,010716,011016",
                    "startOD": "01/01/16",
                    "keyDemos": null,
                    "genres": "Action",
                    "starActrs": "Chris Evans",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Set in a future where a failed climate-change experiment kills all life on the planet, a lucky few board a train that endlessly circles the icy globe with a cruel and dangerous class hierarchy separating the front and back passengers.",
                    "image": null
                },
                {
                    "program": "Vampire Academy ",
                    "premium": "Showtime",
                    "chanName": "Showtime Beyond",
                    "chanNum": "550",
                    "premDate": "01/02/16",
                    "dayWeek": "Saturday ",
                    "finDate": null,
                    "repDates": null,
                    "startOD": "01/02/16",
                    "keyDemos": null,
                    "genres": "Teen Drama",
                    "starActrs": "Zoey Deutch ",
                    "starDrctrs": null,
                    "starPrdcrs": null,
                    "description": "Rose Hathaway is a Dhampir, half human-half vampire, a guardian of the Moroi, peaceful, mortal vampires living discreetly within our world. Her calling is to protect the Moroi from bloodthirsty, immortal Vampires, the Strigoi.",
                    "image": null
                }
            ]
        }
    ]
}};
